# for full syntax documentation see:  https://lgtm.com/help/lgtm/lgtm.yml-configuration-file
path_classifiers:
  test:
    - "*/fuzz_test/**/*"
    - "*/test/**/*"
    - "*/benchmark/**/*"
  library:
    - "*/libs/**/*"
  docs:
    - "*/doc/**"
  generated:
    - "*/img/**"
    - "*/reports/**"
extraction:
  cpp:
    prepare:
      packages:
        - g++-10
        - ccache
      script:
        - mkdir ~/.conan
        - cat /usr/local/share/ca-certificates/semmle-cache-ca/semmle-cache-ca.crt >> ~/.conan/cacert.pem
        - python3 -m pip install --upgrade pip setuptools
        - python3 -m pip install conan
        - python3 -m pip install cmake
        - python3 -m pip install cogapp
        - source ~/.profile
    configure:
      command:
        - git submodule update --remote --recursive
        - git submodule foreach git pull origin master
        - ./vcpkg/bootstrap-vcpkg.sh
        - mkdir build
        - cmake -D OPT_ENABLE_COVERAGE:BOOL=TRUE -D CMAKE_BUILD_TYPE:STRING=Debug -D ENABLE_DEVELOPER_MODE:BOOL=FALSE  -S . -B build
    index:
      build_command: cmake --build ./build -- -j2
